### ISSUE TITLE
ZOCP Samples

### ISSUE THREAD

**Issue by rasteron** [z25/pyZNodeEditor#13]
I find this python port really interesting. Where can I test, find or load .zocp files?

Thanks.

**Comment by rasteron** [comment]
Ah never mind. I actually found what I'm looking for, which is just the port of qnodeeditor.

Thanks anyway. :smile:

**Comment by fieldOfView** [comment]
For completeness:
https://github.com/fieldOfView/pyQNodesEditor

pyQNodesEditor is a fairly straight port of the QNodesEditor. There's an additional branch that adds some prettiness (in my opinion).

pyZNodeEditor (this repo) is an application of the pyQNodesEditor port. It visualizes existing nodes in the ZOCP network; nodes are not created using the pyZNodeEditor, but you can edit certain properties of them.
