### ISSUE TITLE
januari target 

### ISSUE THREAD

**Issue by sphaero** [z25/pyZNodeEditor#2]
Hey Aldo,

I would like to present the node editor at FOSDEM. In order to do so I would like to fix the issue with objects in the capability tree. It would also be nice if the node editor repository is hosted under the z25 organisation. I don't know what your plans are hence this issue but let me know your thoughts.

I've been looking into the objects issue. It would be easiest if we have the cap tree reorganised so we have signal ids to refer to. I have a branch with some initial tests. https://github.com/sphaero/pyZOCP/tree/capability_refactor

**Comment by fieldOfView** [comment]
I'm a little swamped in maplab-work until shortly before FOSDEM.

Ofcourse @z25 is free to fork the editor, but I guess I can also transfer ownership of the project and refork it myself.

**Comment by sphaero** [comment]
I think for history maintenance it's best to move the repo to z25. You are in the z25 organisation on github, right?

**Comment by fieldOfView** [comment]
I would like to finish my "train of thought" with the config manager (see this submodule: https://github.com/fieldOfView/pyZConfigManager), and will transfer ownership once that settles.

**Comment by fieldOfView** [comment]
I have removed the config manager for now. Will return later as a pull request.
Transfering the repo to @z25
